#ifndef CONFIG_H_
#define CONFIG_H_

#include <board/board.h>
#include <stddef.h>

#define INTERRUPT_REALTIME 0
#define INTERRUPT_NORMAL 1
#define INTERRUPT_BELOW_NORMAL 2

#define SCHEDULER_PRIOR_BITS 0x00000002UL
#define SCHEDULER_MAX_IRQ_PRIORITY INTERRUPT_NORMAL
#define SCHEDULER_MIN_IRQ_PRIORITY (SCHEDULER_PRIOR_BITS + 1)

#define SYSTEM_INIT_PRIORITY 000
#define RUNTIME_INIT_PRIORITY 005
#define FAULT_SYSTEM_INIT_PRIORITY 010
#define IRQ_SYSTEM_INIT_PRIORIY 020
#define SWI_SYSTEM_INIT_PRIORIY 021
#define SYSTICK_SYSTEM_INIT_PRIORITY 030

#define BOARD_PLATFORM_INIT_PRIORITY 000
#define BOARD_PLATFORM_DIAG_PRIORITY 010

#define HAL_PLATFORM_PRIORITY 020

#define DEVICES_PLATFORM_PRIORITY 030

#define DIAG_BUFFER_SIZE 256

#define SYSTICK_INTERRUPT_PRIORITY INTERRUPT_NORMAL
#define SVCALL_INTERRUPT_PRIORITY (INTERRUPT_NORMAL + 1)
#define PENDSV_INTERRUPT_PRIORITY (INTERRUPT_NORMAL + 2)

#define MULTICORE_STACK_SIZE 4096UL

#define SCHEDULER_TIME_SLICE 10UL

#endif
